#!/bin/bash

#$ -M drichte2@nd.edu
#$ -m n
#$ -pe mpi-16 64
#$ -q *@@richter
#$ -N case1
#$ -j y


module load mvapich2
module load intel

case=case1
time=0000000
runout=$case.out.$time

datadir=/scratch365/drichte2/NTLP-wavy/$case
homedir=~/Research/NTLP-wavy/$case

cd $homedir

imachine=0
echo $imachine > ./mach.file
echo $datadir >> ./mach.file

mpirun -n 64 $homedir/../build/lesmpi.a $homedir/params.in > $datadir/$runout

